version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers-legacy
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_HOST: 127.0.0.1
          - MYSQL_ALLOW_EMPTY_PASSWORD: "true"

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: mv config/database.yml.ci config/database.yml
      
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec rake db:seed

      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec